import requests


# web_url = ['https://www.universityliving.com/spain/city',
# 'https://www.universityliving.com/italy/city/torino',
# 'https://www.universityliving.com/canada/city/british-columbia',
# 'https://www.universityliving.com/united-states/city/oakland',
# 'https://www.universityliving.com/canada/city/langley',
# 'https://www.universityliving.com/united-states/city/pittsburgh',
# 'https://www.universityliving.com/poland/city/lodz',
# 'https://www.universityliving.com/ireland/city/limerick',
# 'https://www.universityliving.com/poland/city/katowice',
# 'https://www.universityliving.com/italy/city/torino',
# 'https://www.universityliving.com/denmark/city/lyngby',
# 'https://www.universityliving.com/denmark/city/aalborg',
# 'https://www.universityliving.com/united-states/city/mississippi',
# 'https://www.universityliving.com/ireland/city/manchester',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/australia/city/wollongong',
# 'https://www.universityliving.com/united-kingdom/coventry/city-village',
# 'https://www.universityliving.com/united-states/city/pittsburgh',
# 'https://www.universityliving.com/contact/city/raffles-house',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/location/city/sheffield',
# 'https://www.universityliving.com/netherlands/city/leiden',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/united-states/city/hyattsville',
# 'https://www.universityliving.com/united-kingdom/city/brisbane',
# 'https://www.universityliving.com/india/city/pune',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/contact/city/raffles-house',
# 'https://www.universityliving.com/united-states/city/savannah',
# 'https://www.universityliving.com/canada/city/peterborough',
# 'https://www.universityliving.com/canada/city/oakville',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/australia/city/south-yarra',
# 'https://www.universityliving.com/singapore/city',
# 'https://www.universityliving.com/ireland/city/limerick',
# 'https://www.universityliving.com/united-states/city/kent',
# 'https://www.universityliving.com/netherlands/city/leiden',
# 'https://www.universityliving.com/united-states/city/montclair',
# 'https://www.universityliving.com/canada/city/peterborough',
# 'https://www.universityliving.com/united-states/city/university-park',
# 'https://www.universityliving.com/india/city/pune',
# 'https://www.universityliving.com/united-states/city/orange-county',
# 'https://www.universityliving.com/united-states/city/baltimore',
# 'https://www.universityliving.com/united-states/city/montclair',
# 'https://www.universityliving.com/united-kingdom/city/farnham',
# 'https://www.universityliving.com/united-states/city/west-long-branch',
# 'https://www.universityliving.com/canada/city/thunderbay',
# 'https://www.universityliving.com/student-accommodation/city/sheffield',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/france/city/saint-martin-d-heres',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/india/city/gurgaon',
# 'https://www.universityliving.com/contact/city/Kerria-apartments',
# 'https://www.universityliving.com/united-kingdom/city',
# 'https://www.universityliving.com/united-kingdom/manchester/city-edge-manchester',
# 'https://www.universityliving.com/united-kingdom/city/cork',
# 'https://www.universityliving.com/canada/city/charlottetown',
# 'https://www.universityliving.com/united-states/city/dayton',
# 'https://www.universityliving.com/united-states/city/scranton',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-5',
# 'https://www.universityliving.com/ireland/city/leeds',
# 'https://www.universityliving.com/united-arab-emirates/city',
# 'https://www.universityliving.com/italy/city',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-3',
# 'https://www.universityliving.com/united-states/city/cincinnati',
# 'https://www.universityliving.com/united-kingdom/city/nottingham%25C2%25A0',
# 'https://www.universityliving.com/united-states/city/pennsylvania',
# 'https://www.universityliving.com/united-states/city/new-orleans',
# 'https://www.universityliving.com/blog-detail/city/how-to-find-your-second-year-home',
# 'https://www.universityliving.com/united-states/city/south-orange',
# 'https://www.universityliving.com/united-states/city/newark',
# 'https://www.universityliving.com/united-states/city/cincinnati',
# 'https://www.universityliving.com/united-states/city/missouri',
# 'https://www.universityliving.com/united-states/city/glassboro',
# 'https://www.universityliving.com/united-states/city/orlando',
# 'https://www.universityliving.com/united-states/city/teaneck',
# 'https://www.universityliving.com/italy/city/siena',
# 'https://www.universityliving.com/germany/hamburg/property/city-loft-at-the-park-medium-maisonette',
# 'https://www.universityliving.com/united-states/city/university-park',
# 'https://www.universityliving.com/united-states/city/$SJ_PULSE_DESKTOP_API_URL$/storage/loggerQueue',
# 'https://www.universityliving.com/united-states/city/colorado-spring',
# 'https://www.universityliving.com/united-states/city/florida',
# 'https://www.universityliving.com/germany/city/bingen',
# 'https://www.universityliving.com/united-states/city/florida',
# 'https://www.universityliving.com/australia/city/sunshine-coast',
# 'https://www.universityliving.com/united-kingdom/city/exeter&quot',
# 'https://www.universityliving.com/united-kingdom/city/staffordshire',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/denmark/city/lyngby',
# 'https://www.universityliving.com/united-kingdom/coventry/city-point',
# 'https://www.universityliving.com/blog/city/explore-adelaide-south-australias-cosmopolitan',
# 'https://www.universityliving.com/india/city/chandigarh',
# 'https://www.universityliving.com/netherlands/city/leiden',
# 'https://www.universityliving.com/new-zealand/city/christchurch',
# 'https://www.universityliving.com/germany/city/munster%2522',
# 'https://www.universityliving.com/united-kingdom/coventry/city-point',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/united-states/city/west-lafayette',
# 'https://www.universityliving.com/united-states/city/irvine%255Dstudent',
# 'https://www.universityliving.com/united-kingdom/leeds/p/cityside',
# 'https://www.universityliving.com/united-states/city/princeton',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/united-kingdom/coventry/city-village',
# 'https://www.universityliving.com/united-kingdom/city',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/netherlands/city/enschede',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-7',
# 'https://www.universityliving.com/united-kingdom/coventry/city-point',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-8',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/ireland/city/manchester',
# 'https://www.universityliving.com/germany/leipzig/property/city-center-design-premium-apartments',
# 'https://www.universityliving.com/united-states/city/wichita',
# 'https://www.universityliving.com/canada/city/newfoundland',
# 'https://www.universityliving.com/united-kingdom/coventry/city-village',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/united-kingdom/coventry/city-village',
# 'https://www.universityliving.com/properties/city/58a420caa5984db749fa8a9f-wimslow-park-house',
# 'https://www.universityliving.com/italy/city/pavia',
# 'https://www.universityliving.com/united-states/city/baltimore',
# 'https://www.universityliving.com/germany/hamburg/property/city-apartment-with-in-the-speicherstadt',
# 'https://www.universityliving.com/netherlands/city/leiden',
# 'https://www.universityliving.com/united-states/city/west-lafayette',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-8',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-5',
# 'https://www.universityliving.com/united-arab-emirates/city',
# 'https://www.universityliving.com/united-states/city/kent',
# 'https://www.universityliving.com/india/city/guwahati',
# 'https://www.universityliving.com/united-states/city/boca-raton',
# 'https://www.universityliving.com/united-states/city/hyattsville',
# 'https://www.universityliving.com/germany/berlin/property/city-center-design-premium-apartments-4',
# 'https://www.universityliving.com/contact/city/Kerria-apartments',
# 'https://www.universityliving.com/united-kingdom/city/ci',
# 'https://www.universityliving.com/united-kingdom/city/dublin',
# 'https://www.universityliving.com/denmark/city/lyngby',
# 'https://www.universityliving.com/united-states/city/california',
# 'https://www.universityliving.com/united-states/city/hyattsville',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/australia/city/south-yarra',
# 'https://www.universityliving.com/united-states/city/west-long-branch',
# 'https://www.universityliving.com/united-states/city/$SJ_PULSE_DESKTOP_API_URL$/storage/loggerQueue',
# 'https://www.universityliving.com/canada/city',
# 'https://www.universityliving.com/united-states/city/hoboken',
# 'https://www.universityliving.com/italy/city/genova',
# 'https://www.universityliving.com/india/city/pune',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/united-kingdom/manchester/city-edge-manchester',
# 'https://www.universityliving.com/properties/city/woburn-place',
# 'https://www.universityliving.com/united-kingdom/reading/city-block-1-reading',
# 'https://www.universityliving.com/united-states/city/maryland',
# 'https://www.universityliving.com/united-arab-emirates/city',
# 'https://www.universityliving.com/united-states/city/kent',
# 'https://www.universityliving.com/united-kingdom/city/galway',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/australia/city/new-south-wales',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-9',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/united-kingdom/city/galway',
# 'https://www.universityliving.com/united-kingdom/manchester/city-edge-manchester',
# 'https://www.universityliving.com/united-states/city/mississippi',
# 'https://www.universityliving.com/united-kingdom/city/sydney',
# 'https://www.universityliving.com/germany/frankfurt/property/city-center-design-premium-apartments-5',
# 'https://www.universityliving.com/united-kingdom/reading/city-block-1-reading',
# 'https://www.universityliving.com/ireland/city/dublin&sa=U&ved=2ahUKEwid78ne6qb8AhW5DRAIHRX5BhIQFnoECAgQAg&usg=AOvVaw3WNckNQ_GQHENx6qmHqfgo',
# 'https://www.universityliving.com/portugal/city/montreal',
# 'https://www.universityliving.com/united-states/city/hoboken',
# 'https://www.universityliving.com/united-kingdom/reading/city-block-1-reading',
# 'https://www.universityliving.com/australia/city/wollongong',
# 'https://www.universityliving.com/student-accommodation/city/bristol',
# 'https://www.universityliving.com/united-kingdom/city/farnham',
# 'https://www.universityliving.com/united-kingdom/city/cork',
# 'https://www.universityliving.com/united-kingdom/city/brisbane',
# 'https://www.universityliving.com/italy/city/venice',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/india/city/indore',
# 'https://www.universityliving.com/germany/city/muns',
# 'https://www.universityliving.com/australia/city/south-yarra',
# 'https://www.universityliving.com/united-kingdom/city/auckland',
# 'https://www.universityliving.com/italy/city/venice',
# 'https://www.universityliving.com/united-kingdom/leeds/cityside/book-now/thank-you',
# 'https://www.universityliving.com/poland/city/katowice',
# 'https://www.universityliving.com/germany/berlin/property/city-center-design-premium-apartments-3',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/australia/city/null',
# 'https://www.universityliving.com/united-kingdom/city/nJi5etcyZPQx/t4cs2R7byg9VWJ9QPGs',
# 'https://www.universityliving.com/united-states/city/wichita',
# 'https://www.universityliving.com/united-states/city/princeton',
# 'https://www.universityliving.com/united-states/city/west-lafayette',
# 'https://www.universityliving.com/italy/city/venice',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/india/city/vadodara',
# 'https://www.universityliving.com/italy/city/fiumicino',
# 'https://www.universityliving.com/india/city/dehradun',
# 'https://www.universityliving.com/united-kingdom/leeds/cityside',
# 'https://www.universityliving.com/united-kingdom/leeds/cityside',
# 'https://www.universityliving.com/united-kingdom/reading/city-block-1-reading',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/united-states/city/thousand-oaks',
# 'https://www.universityliving.com/united-states/city/thousand-oaks',
# 'https://www.universityliving.com/australia/city/ADELAIDE',
# 'https://www.universityliving.com/australia/city/wollongong',
# 'https://www.universityliving.com/united-states/city/pittsburgh',
# 'https://www.universityliving.com/united-kingdom/reading/city-block-1-reading',
# 'https://www.universityliving.com/united-states/city/syracuse',
# 'https://www.universityliving.com/india/city/pune',
# 'https://www.universityliving.com/new-zealand/city/christchruch',
# 'https://www.universityliving.com/united-states/city/maryland',
# 'https://www.universityliving.com/united-states/city/syracuse',
# 'https://www.universityliving.com/india/city/ahmedabad',
# 'https://www.universityliving.com/united-states/city/tallahas',
# 'https://www.universityliving.com/united-states/city/tallahas',
# 'https://www.universityliving.com/united-states/city/nebraska',
# 'https://www.universityliving.com/united-states/city/cincinnati',
# 'https://www.universityliving.com/united-states/city/west-haven',
# 'https://www.universityliving.com/india/city/pune',
# 'https://www.universityliving.com/netherlands/city/enschede',
# 'https://www.universityliving.com/italy/city/fiumicino',
# 'https://www.universityliving.com/united-states/city/savannah',
# 'https://www.universityliving.com/australia/city/new-south-wales',
# 'https://www.universityliving.com/united-kingdom/city',
# 'https://www.universityliving.com/ireland/city/coventry',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/united-states/city/thousand-oaks',
# 'https://www.universityliving.com/australia/city/wollongong',
# 'https://www.universityliving.com/united-kingdom/leeds/citysid',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/united-kingdom/coventry/city-village',
# 'https://www.universityliving.com/united-kingdom/cardiff/city-heights-cardiff',
# 'https://www.universityliving.com/united-kingdom/city',
# 'https://www.universityliving.com/ireland/city/newport',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-7',
# 'https://www.universityliving.com/contact/city/raffles-house',
# 'https://www.universityliving.com/ireland/city/coventry',
# 'https://www.universityliving.com/united-states/city/kent',
# 'https://www.universityliving.com/united-states/city/kent',
# 'https://www.universityliving.com/united-states/city/kent',
# 'https://www.universityliving.com/united-kingdom/durham/cityblock-the-village',
# 'https://www.universityliving.com/italy/city/venice',
# 'https://www.universityliving.com/italy/city/venice',
# 'https://www.universityliving.com/properties/city/woburn-place',
# 'https://www.universityliving.com/united-states/city/hyattsville',
# 'https://www.universityliving.com/united-states/city/colarado-spring',
# 'https://www.universityliving.com/united-kingdom/city/galway',
# 'https://www.universityliving.com/united-states/city/cincinnati',
# 'https://www.universityliving.com/australia/city/london',
# 'https://www.universityliving.com/australia/city/london',
# 'https://www.universityliving.com/australia/city/london',
# 'https://www.universityliving.com/australia/city/london',
# 'https://www.universityliving.com/australia/city/london',
# 'https://www.universityliving.com/ireland/city/york',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-3',
# 'https://www.universityliving.com/france/city/Sorbonne',
# 'https://www.universityliving.com/poland/city/katowice',
# 'https://www.universityliving.com/italy/city/barbaresco',
# 'https://www.universityliving.com/united-states/city/orlando',
# 'https://www.universityliving.com/united-kingdom/city/brisbane',
# 'https://www.universityliving.com/united-states/city/newyork%2522%253EKeyword/text%253C/a%253Estudent',
# 'https://www.universityliving.com/australia/city',
# 'https://www.universityliving.com/united-states/city/weatherford',
# 'https://www.universityliving.com/united-kingdom/city/cork',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/canada/city/barrieQuality%2520Student%2520Accommodation%2520in%2520Barrie%2520%257C%2520University%2520Living',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/new-zealand/city/christchurch',
# 'https://www.universityliving.com/italy/city/genova',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/india/city/delhi',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/united-kingdom/city/galway',
# 'https://www.universityliving.com/united-kingdom/city/cork',
# 'https://www.universityliving.com/india/city/hyderabad',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/united-states/city/new-jersey',
# 'https://www.universityliving.com/germany/leipzig/property/city-center-design-premium-apartments',
# 'https://www.universityliving.com/australia/city/melbo',
# 'https://www.universityliving.com/australia/city/mel',
# 'https://www.universityliving.com/australia/city/melb',
# 'https://www.universityliving.com/australia/city/melbour',
# 'https://www.universityliving.com/australia/city/melbou',
# 'https://www.universityliving.com/australia/city/me',
# 'https://www.universityliving.com/australia/city/melbourn',
# 'https://www.universityliving.com/australia/city',
# 'https://www.universityliving.com/india/city/bangalore',
# 'https://www.universityliving.com/united-states/city/maryland',
# 'https://www.universityliving.com/australia/city/Adelaide',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/united-kingdom/city/cork',
# 'https://www.universityliving.com/united-kingdom/coventry/city-point',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-7',
# 'https://www.universityliving.com/india/city/pune',
# 'https://www.universityliving.com/united-kingdom/leeds/cityside/book-now/thank-you',
# 'https://www.universityliving.com/united-kingdom/leeds/cityside',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/united-kingdom/city/farnham',
# 'https://www.universityliving.com/spain/barcelona/property/city-center-1-room-with-balcony-5',
# 'https://www.universityliving.com/italy/city/lampedusa-e-linosa',
# 'https://www.universityliving.com/united-kingdom/lancaster/cityblock-lancaster',
# 'https://www.universityliving.com/united-kingdom/city/galway',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/india/city/gurgaon',
# 'https://www.universityliving.com/denmark/city/lyngby',
# 'https://www.universityliving.com/ireland/city/limerick',
# 'https://www.universityliving.com/poland/city/lodz',
# 'https://www.universityliving.com/canada/city/peterborough',
# 'https://www.universityliving.com/germany/frankfurt/property/city-center-design-premium-apartments-5',
# 'https://www.universityliving.com/australia/city/malvern-east',
# 'https://www.universityliving.com/united-states/city/princeton',
# 'https://www.universityliving.com/united-states/city/pennsylvania',
# 'https://www.universityliving.com/united-states/city/big-rapids',
# 'https://www.universityliving.com/canada/city/oakville',
# 'https://www.universityliving.com/united-kingdom/city/preston&quot',
# 'https://www.universityliving.com/italy/city/siena',
# 'https://www.universityliving.com/united-states/city/rocklin',
# 'https://www.universityliving.com/united-states/city/teaneck',
# 'https://www.universityliving.com/india/city/mumbai',
# 'https://www.universityliving.com/united-states/city/pittsburgh',
# 'https://www.universityliving.com/united-states/city/thousand-oaks',
# 'https://www.universityliving.com/india/city/noida',
# 'https://www.universityliving.com/united-states/city/orlando',
# 'https://www.universityliving.com/united-states/city/south-orange',
# 'https://www.universityliving.com/nepal/city/kathmandu',
# 'https://www.universityliving.com/student-accommodation/city/bristol',
# 'https://www.universityliving.com/contact/city/Kerria-apartments',
# 'https://www.universityliving.com/india/city/guwahati','https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
# 'https://www.universityliving.com/united-kingdom/london/place/elephant-and-castle,18,13,1,2,10,913',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
# 'https://www.universityliving.com/australia/springvale/place/springvale',
# 'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
# 'https://www.universityliving.com/js/src/client/assets/details/images/placeholder.svg',
# 'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
# 'https://www.universityliving.com/australia/springvale/place/springvale',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
# 'https://www.universityliving.com/australia/springvale/place/springvale',
# 'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/springvale/place/springvale',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
# 'https://www.universityliving.com/js/src/client/assets/details/images/placeholder.svg',
# 'https://www.universityliving.com/australia/springvale/place/springvale',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
# 'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
# 'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
# 'https://www.universityliving.com/australia/springvale/place/springvale',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/box-hill/place/box-hill',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
# 'https://www.universityliving.com/australia/south-yarra/place/south-yarra'

# ]

web_url = [
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
'https://www.universityliving.com/united-kingdom/london/place/elephant-and-castle,18,13,1,2,10,913',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
'https://www.universityliving.com/australia/springvale/place/springvale',
'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
'https://www.universityliving.com/js/src/client/assets/details/images/placeholder.svg',
'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
'https://www.universityliving.com/australia/springvale/place/springvale',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
'https://www.universityliving.com/australia/springvale/place/springvale',
'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/springvale/place/springvale',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
'https://www.universityliving.com/js/src/client/assets/details/images/placeholder.svg',
'https://www.universityliving.com/australia/springvale/place/springvale',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/malvern-east/place/malvern-east',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/craigieburn/place/craigieburn',
'https://www.universityliving.com/australia/north-melbourne/place/north-melbourne',
'https://www.universityliving.com/australia/sunshine-coast/place/sunshine-coast',
'https://www.universityliving.com/australia/springvale/place/springvale',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/box-hill/place/box-hill',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',
'https://www.universityliving.com/australia/south-yarra/place/south-yarra',


]
status = {200:"available",301:"permanent redirect",302:"Temp redirect",404:"not found",500:"internal server error",503:"service unavailable"}

for url in web_url:
    
    try:
        web_response = requests.get(url)
        a = status[web_response.status_code]
        if a == "available":
            print(url,a)
        else:
            pass

    except:
        web_response = requests.get(url)
        a = status[web_response.status_code]
        if a == "available":
            print(url,a)
        else:
            pass

